"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var MessageType;
(function (MessageType) {
    MessageType["TEXT"] = "text";
    MessageType["IMAGE"] = "image";
    MessageType["VOICE"] = "voice";
    MessageType["VIDEO"] = "video";
    MessageType["MUSIC"] = "music";
    MessageType["NEWS"] = "news";
    MessageType["SHORT_VIDEO"] = "shortvideo";
    MessageType["LOCATION"] = "location";
    MessageType["LINK"] = "link";
    MessageType["DEVICE_EVENT"] = "deviceevent";
    MessageType["DEVICE_TEXT"] = "devicetext";
    MessageType["FILE"] = "file";
    MessageType["TEXT_CARD"] = "textcard";
    MessageType["TRANSFER"] = "transfer";
    MessageType["EVENT"] = "event";
    MessageType["UNKNOWN"] = "unknown";
})(MessageType || (MessageType = {}));
exports.default = MessageType;
